### ISSUE TITLE
Add our own airports in the database

### ISSUE THREAD

**Issue by maesteve** [vsimakhin/web-logbook#107]
Some small airports do not have an ICAO code and are not shown on the map.

Being able to create our database with those airports so that it can be represented on the map together with the default airport database.

**Comment by Jacopx** [comment]
I agree, I have added an entry directly on the SQLite DB, for the ICAO part I have added the name the I use in the logbook.

Could be useful in case of helicopter pilot like me.

**Comment by vsimakhin** [comment]
ok, will take a look

**Comment by vsimakhin** [comment]
preparing first beta https://github.com/vsimakhin/web-logbook/pull/108, will test it a little bit more and then release a new version

**Comment by vsimakhin** [comment]
The new version 2.16.0 has been released. I will close this "issue", so please take a look if it's ok, and feel free to reopen it if it's not :)
