### ISSUE TITLE
Remark visualization with big boxes

### ISSUE THREAD

**Issue by Jacopx** [vsimakhin/web-logbook#118]
The remarks column show online a small part of the text inside the field even if the box is bigger:

![image](https://user-images.githubusercontent.com/14002538/229738269-32d3665e-f80a-4e7a-8019-a3bbff86c92a.png)

The content of that box, in this specific case is: "PPL-H Check Ride"

**Comment by vsimakhin** [comment]
This will be fixed with upcoming changes with sync option https://github.com/vsimakhin/web-logbook/pull/117/files#diff-99a4bc6006bb72b9ad9b95b23646565a8f97191f64f1e62394bf6db1ea81ee1dL51
