### ISSUE TITLE
Lateral table spacing

### ISSUE THREAD

**Issue by Jacopx** [vsimakhin/web-logbook#119]
Is really a minor stuff, the path on the left, the orange one, is correct and well-balanced, the one on the right, blue, is too small:

![image](https://user-images.githubusercontent.com/14002538/229739367-dfb00d1c-c184-4075-a29f-da767f24461c.png)

Having the same spacing could improve the general style of this page.

**Comment by vsimakhin** [comment]
I don't know how to do that :) It's sort of advanced web design with styles and so on, and I'm not good at it :)

**Comment by vsimakhin** [comment]
I think I will be able to "fix" it once I update Bootstrap lib to the newer version, which supports dark mode. I plan to use theirs new updated dashboard example
