### ISSUE TITLE
Number in chart decimal

### ISSUE THREAD

**Issue by Jacopx** [vsimakhin/web-logbook#120]
The number in the chart is in decimal and not in hh:mm format:

![image](https://user-images.githubusercontent.com/14002538/229850964-91b20c6e-70ae-4862-931b-c4cd0999ff25.png)

The pop-up windows should show 98:58 (hh:mm) and not 98.98 the is the decimal version of the correct one.

**Comment by vsimakhin** [comment]
So if you take 58 minutes, it will be ~ 0.98 hours. I had to set decimal values for the chart, otherwise, it couldn't correctly draw it. I will take a look if I can change the pop-up values to the proper hh:mm format

**Comment by Jacopx** [comment]
Yes, I've understand the mathematical conversion, but reading 98.98 make that chart less useful for comparisons, in any case not a big deal.
