### ISSUE TITLE
Remark visualization for big boxes with big text

### ISSUE THREAD

**Issue by Jacopx** [vsimakhin/web-logbook#122]
I know that you hate me, but I'm a software engineer too and i like to break things.

Referring to #118 the problem is now different:

![image](https://user-images.githubusercontent.com/14002538/230437059-6f0ed75a-a182-46f6-ad26-c3fc4995c058.png)

When the remark is really long the visualization crash.

**Comment by vsimakhin** [comment]
:))) Looks like I will need to calculate it somehow dynamically, when the table is generated and check the screen size

**Comment by vsimakhin** [comment]
[Screencast from 2023-04-08 11-03-51.webm](https://user-images.githubusercontent.com/139220/230713373-aa7010b6-ca46-4a96-866d-6a280ed8c0ab.webm)

But I think it will depend on the screen resolution...
