### ISSUE TITLE
Add opening totals

### ISSUE THREAD

**Issue by dimoniet** [vsimakhin/web-logbook#129]
Add fields to allow the user put their previous experience without the need to enter all the flights.

**Comment by vsimakhin** [comment]
What should it look like in the logbook? Numbers go to the "Total from previous" on the first page or are they just a first line on the first page?
![image](https://user-images.githubusercontent.com/139220/232199146-937bd343-c9f5-4f98-bb4d-8e3d478e4c32.png)

**Comment by vsimakhin** [comment]
theoretically, I can make an option to add bigger flight hours for the flight record, so the opening totals will be just a simple first flight record

![image](https://user-images.githubusercontent.com/139220/232200114-c72d9486-9782-4267-9fae-b2023c821ee5.png)

just will need to update the validators

**Comment by vsimakhin** [comment]
like this 
![image](https://user-images.githubusercontent.com/139220/232203089-e52ed265-2e65-458e-95a4-f39d880015b0.png)

and this
![image](https://user-images.githubusercontent.com/139220/232203122-b7ea246f-5dee-46cc-b65a-e0ee2be64ce3.png)
![image](https://user-images.githubusercontent.com/139220/232203146-abe79718-e4a5-4e07-a91d-542935818153.png)

**Comment by dimoniet** [comment]
Great job, and really fast!! Sorry for not answering before!
