### ISSUE TITLE
[BROKEN] Can't insert data after lastest update

### ISSUE THREAD

**Issue by Jacopx** [vsimakhin/web-logbook#134]
After the last update the auotmatic data not does not work and i can't submit a new flight, related maybe with #129 

![image](https://user-images.githubusercontent.com/14002538/232221391-f7589235-899e-463c-af70-6ca6c0c222b8.png)

**Comment by vsimakhin** [comment]
ops... checking it

**Comment by vsimakhin** [comment]
should be fixed now, new release is published
