### ISSUE TITLE
Last update change something

### ISSUE THREAD

**Issue by Jacopx** [vsimakhin/web-logbook#140]
I've make the last update and, fare the build i've copied back my SQLite DB inside the dist folder, as always (automatized by a script), now the flight tab and the licesing are empty, the other are populated.

Is something in the structure of the DB changed?

**Comment by vsimakhin** [comment]
Nope... can you run it with `-env dev` flag to check the logs?

**Comment by vsimakhin** [comment]
Oh... I was sort of "fixing" the pagination for the main logbook page, which includes the flights and licensing table. Can you check in Settings->Misc these fields
![image](https://user-images.githubusercontent.com/139220/234507196-f91151b7-883e-4086-97db-c0ae9133d521.png)

**Comment by vsimakhin** [comment]
and if you can check page source
![image](https://user-images.githubusercontent.com/139220/234511070-8c6a715d-5302-43d9-81b0-b3833a3b6ff6.png)
the line 239 with `var lengthMenu`

**Comment by Jacopx** [comment]
Same as your and also the Misc fields. I have also tried with all the most common browser.

<img width="1680" alt="Screenshot 2023-04-26 at 23 42 34" src="https://user-images.githubusercontent.com/14002538/234709409-0ddedb8e-6e59-46a4-8915-95a11d69d516.png">

**Comment by vsimakhin** [comment]
fixed with the latest release
