### ISSUE TITLE
Add proper readme/howto

### ISSUE THREAD

**Issue by vsimakhin** [vsimakhin/web-logbook#15]

**Comment by vsimakhin** [comment]
nah, I think this "issue" will be here forever :)

**Comment by Jacopx** [comment]
Could I help you? What do you want to improve?

**Comment by vsimakhin** [comment]
hey @Jacopx! Any help is appreciated! I'm not good at writing documentation at all, so might make it a little bit more user-friendly? I'm a developer, so it's hard for me to take a look at the app as a normal user who doesn't know all the technical details :)
