### ISSUE TITLE
Evaluate OurAirports for Airport database

### ISSUE THREAD

**Issue by maesteve** [vsimakhin/web-logbook#152]
https://ourairports.com/
https://davidmegginson.github.io/ourairports-data/

The gps_code field for each aerodrome is the ICAO code.

Aerodromes without gps_code can use the name or municipality attributes to display in the logbook. The ident attribute for internal database use.

**Comment by vsimakhin** [comment]
Started working on it
![image](https://github.com/vsimakhin/web-logbook/assets/139220/2742048d-ec05-4c50-aa8f-c185e6bbde6a)

![image](https://github.com/vsimakhin/web-logbook/assets/139220/a6862ec0-9e7e-4ffa-801d-f1f0b9f81531)

I think if there is no gps_code it's better to take the is from 'ident' table. At least this one doesn't change within OurAirports DB and you can always find it in theirs list
