### ISSUE TITLE
Aircraft Class filter in the Maps section not work

### ISSUE THREAD

**Issue by ghost** [vsimakhin/web-logbook#155]

**Comment by vsimakhin** [comment]
Can you provide more details, I cannot reproduce the bug. It works for me and the only thing is you need to click on the Refresh button

**Comment by maesteve** [comment]
I select one "Aircraft Class" from the available list and press the refresh button. No results are shown on the map.

I have tried different dates and the "Aircraft Class" filter never shows me results.

**Comment by maesteve** [comment]
If "Aircraft Class" has spaces, the filter does not work.

For example:
TECNAMP92 Ok
TECNAM P92 Fail

**Comment by vsimakhin** [comment]
thanks, will check it
