### ISSUE TITLE
In the logbook view, show a row with totals

### ISSUE THREAD

**Issue by maesteve** [vsimakhin/web-logbook#162]
In the logbook view, show a row with total for the following columns:

* Total Time
* Landings Day/Night
* Operational Condition Time Night/IFR
* Pilot Function Time PIC/COP/Dual/Instr
* FSTD Session Time

Total values for each column are updated when modify the filters

**Comment by vsimakhin** [comment]
![image](https://github.com/vsimakhin/web-logbook/assets/139220/d3fbf79b-de2c-4d76-89e8-f68fe75e4652)

**Comment by vsimakhin** [comment]
will release it soon
