### ISSUE TITLE
Define IPs and port to listen on

### ISSUE THREAD

**Issue by maesteve** [vsimakhin/web-logbook#169]
Listen on all IPs of all available interfaces now.

Being able to define which IPs to listen on along with their port.

By default, only listen on localhost 127.0.0.1

**Comment by vsimakhin** [comment]
This one is already implemented with params `url` and `port`:
```
Usage of ./web-logbook:
  -cert string
    	certificate path (default "certs/localhost.pem")
  -disable-authentication
    	Disable authentication (in case you forgot login credentials)
  -dsn string
    	SQLite file name (default "web-logbook.sql")
  -enable-https
    	Enable TLS/HTTPS
  -env string
    	Environment {dev|prod} (default "prod")
  -key string
    	private key path (default "certs/localhost-key.pem")
  -port int
    	Server port (default 4000)
  -url string
    	Server URL (default "localhost")
  -version
    	Prints current version
```

**Comment by maesteve** [comment]
If you run ./web-logbook -url localhost in Settings -> Sync all IPs listening are shown, not only localhost 127.0.0.1

If you access with an IP of those shown you can access and access is not restricted to localhost.

**Comment by vsimakhin** [comment]
ah, now I got what you mean...

**Comment by vsimakhin** [comment]
hah, it looks like I never used `url` param and the app always listens on all available IPs :)
```
Addr:     fmt.Sprintf(":%d", app.config.port),
```
Ok, I will make a fix

**Comment by maesteve** [comment]
Continue listen on all network interfaces. Tested with:

./web-logbook -url 127.0.0.1
./web-logbook -url localhost
