### ISSUE TITLE
Cross Country field (This Month, This year) not show 0:00

### ISSUE THREAD

**Issue by Jacopx** [vsimakhin/web-logbook#174]
Hi dear,

the cross country field for: This Month and This year not show 0:00 (that would be correct in my case) like all other fields with a sum of 0:00.

![image](https://github.com/vsimakhin/web-logbook/assets/14002538/abb5df8b-e89b-4a4a-80eb-a9351eb53eae)

**Comment by vsimakhin** [comment]
hm... interesting, will take a look
