### ISSUE TITLE
Not all airfields with ICAO code of source OurAirports are shown

### ISSUE THREAD

**Issue by maesteve** [vsimakhin/web-logbook#179]
If you filter to show only airfields with ICAO code some are not included, e.g. LEVY

Its id is ES-0052 not the ICAO code. The ICAO codes are found in the gps_code attribute.

**Comment by vsimakhin** [comment]
ok, I need to update the way I import data. The thing is, if I take gps_code as ICAO field - there will be duplicates

**Comment by vsimakhin** [comment]
And ES-0052  is for sure a not usable code to have it in the logbook...

**Comment by maesteve** [comment]
Other example, ES-0090 with ICAO code LEVL.

This happens when the airfield is created in OurAirports and does not yet have an ICAO code and is assigned to it later.

**Comment by vsimakhin** [comment]
If you take a look at `LELI` code in the airports.csv file. There is one with gps_code = LELI and it's a small airfield El Molinillo Airfield with internal code ES-0190. There is also a record with internal code LELI without gps_code and it's a small airfield (probably ultralight?) Aeródromo de Linares. And I don't know how to better resolve the "conflict" here.. obviously the airfield with ICAO code has priority, but what to do with another one? I can set ICAO = 'AERODROME DE LINARES' in the database, but it will "brake" the logbook export due to length of the field, and in case the name is changes - it will be lost within the next update.

**Comment by vsimakhin** [comment]
Might be, as a solution for example I provided, I can make ICAO = 'AERODROME DE LINARES' - yes, it will be a long one, but I can add a "copy" button to the airport db view, which will copy the record to the "Custom Airports DB" and then it will be possible to update/change it to have it more friendly in the logbook. So in this case we sort of will have the bigger DB with all the small airfields, and also it will be "maintainable".

You thoughts?

**Comment by vsimakhin** [comment]
Hm.. still will not work due to lot of duplicates in ICAO
```
MILLIPORE HELIPORT|2
MILLER ARMY AIRFIELD|2
MILLER AIRPORT|4
MILITARY RUNWAY|2
MILITARY HELIPAD|12
MIKI HELIPORT|3
MIDWAY AIRPORT|5
MIDLAND AIRPORT|2
```

**Comment by maesteve** [comment]
> If you take a look at `LELI` code in the airports.csv file. There is one with gps_code = LELI and it's a small airfield El Molinillo Airfield with internal code ES-0190. There is also a record with internal code LELI without gps_code and it's a small airfield (probably ultralight?) Aeródromo de Linares. And I don't know how to better resolve the "conflict" here.. obviously the airfield with ICAO code has priority, but what to do with another one? I can set ICAO = 'AERODROME DE LINARES' in the database, but it will "brake" the logbook export due to length of the field, and in case the name is changes - it will be lost within the next update.

El Molinillo Airfield with internal code ES-0190 and gps_code LELI is correct. Available in the AIP
https://aip.enaire.es/aip/contenido_AIP/GEN/LE_GEN_2_4_en.pdf

The ICAO code can only be obtained and is valid from the gps_code field. The ICAO code of an aerodrome can be lost and assigned to another aerodrome.

That is why the value of the id field is not valid, only gps_code.
