### ISSUE TITLE
Time fields on logbook not standard

### ISSUE THREAD

**Issue by ken340** [vsimakhin/web-logbook#191]
The logbook will show the time based on how it was inserted. For example, when key in 04:00 it will show 04:00 and when key in 4:00 it will show 4:00.

can we have it displayed the same I.e 4:00 or 04:00 for all irregardless how it is typed.

**Comment by vsimakhin** [comment]
Yep, I will add sort of format function and several options to the settings page. Just need to find some free time, this month I'm doing a new type rating and I'm very limited with free days.
