### ISSUE TITLE
The map a slightly bigger than page

### ISSUE THREAD

**Issue by Jacopx** [vsimakhin/web-logbook#193]
After changing to the map page, the box where the actual map is contained, is a little bigger than the actual screen available and the scroll bar is necessary to be seen in total:

![image](https://github.com/vsimakhin/web-logbook/assets/14002538/cad8d443-6faa-4453-b487-21391d9f6eaf)

it seems that the fitting of the page is not working perfectly. As you can see the MAP title is a little bit above the normal position after changing page.

**Comment by vsimakhin** [comment]
What screen resolution do you use?

**Comment by Jacopx** [comment]
> What screen resolution do you use?

MacBook with Retina display with default settings: 2880x1800
