### ISSUE TITLE
Licence number and address

### ISSUE THREAD

**Issue by ed03564** [vsimakhin/web-logbook#194]
Could you add "Holder's license number " and "Holder's address"?

**Comment by vsimakhin** [comment]
Do you mean for the pdf export?

**Comment by ed03564** [comment]
> Do you mean for the pdf export?

Yes

**Comment by vsimakhin** [comment]
![image](https://github.com/vsimakhin/web-logbook/assets/139220/ba5cb24d-efa6-41da-b785-f0f3a4d0ad20)

**Comment by vsimakhin** [comment]
I think I will add in future an option to the export settings to add a custom front page...
