### ISSUE TITLE
Import not working (and not telling me why)

### ISSUE THREAD

**Issue by hisetip** [vsimakhin/web-logbook#210]
Howdy! I tried using the import, tried to copy the right format as the export, but after the mapping fields dialog, when I click continue, nothing happens—no error message, etc. I assume it's because there is an incompatible column in the CSV, but I don't know which column is, which makes it impossible to debug/solve. Any way to see an error log or something? Checked the "normal" .log and doesn't contain anything relevant.

**Comment by hisetip** [comment]
Update: after many hours, found the problem. I was passing the date field in the (slightly) wrong format. Would be nice to maybe have a --verbose flag so that (all) errors would logged to the console and people can find out more easily where they're messing up on the import.

**Comment by vsimakhin** [comment]
Hey! Hm, that's interesting. Are you able to share some csv example? If the error is handled, it should be printed in the normal log. And even if it throws the exception, still should be there. Probably, there is something on the UI side in the javascript, which I didn't handle.
