### ISSUE TITLE
Element sizing

### ISSUE THREAD

**Issue by Jacopx** [vsimakhin/web-logbook#215]
First stuff I love the new desing. Good job man!

What i'm here to describe is a problem already shown in #193, several pages and element, in the right main part of the layout not perfectly fitted for navigation without scrolling.

To be specific, this is a page where the page need a scroll:

![immagine](https://github.com/vsimakhin/web-logbook/assets/14002538/68052694-03ce-4c25-aa71-df06eeaf89d3)

and this is a page that not require scroll:

![immagine](https://github.com/vsimakhin/web-logbook/assets/14002538/83069414-bdbf-41ad-99ac-84df2123e087)

I understand that the stuff is related to the resolution/zoom/screen, etc... But It would be really beautiful if the fitting was dynamic.

Here for any clarification or help that I could provide.

**Comment by Jacopx** [comment]
I'm adding a list of page not correctly fitted for my case:

- Logbook
- Map
- Statistics: Total
- Export: PDF A4 (but I think that in this page a scroll is acceptable)
- Export: PDF A5 (but I think that in this page a scroll is acceptable)
- Settings: General (but I think that in this page a scroll is acceptable)

**Comment by vsimakhin** [comment]
Hey! Thanks for the feedback! Yep, I still need to review some page elements. What is your screen resolution just for reference?

**Comment by vsimakhin** [comment]
I found it in the previous #193 - 2880x1800 :)

**Comment by vsimakhin** [comment]
can you show the screenshots for export pdf and settings pages?

**Comment by Jacopx** [comment]
> I found it in the previous #193 - 2880x1800 :)

Fortunately I've upgrade my macbook, now is: 3024 x 1964. The issues is still present with 4K of my external monitor with a bit different behaviour.

**Comment by vsimakhin** [comment]
I released some dynamic sizing for chart for the stats pages. Did it fix the issue at least a little bit? :)
