### ISSUE TITLE
After reducing sub menu a new click will expand them again

### ISSUE THREAD

**Issue by Jacopx** [vsimakhin/web-logbook#216]
After closing one sub menu of the list from the left bar, from this:

![immagine](https://github.com/vsimakhin/web-logbook/assets/14002538/bd03e777-1c1a-476b-8404-ca8110a993e7)

to this:

![immagine](https://github.com/vsimakhin/web-logbook/assets/14002538/450aa4b9-60fc-473f-81e8-97bd139d9c8a)

The next click in any of the left menus will change the page and expand all the closed sub menu again.

I think that leaving the sub-menu as the user have left it is better, this is my humble opinion.

**Comment by vsimakhin** [comment]
Nice catch! Will check it

**Comment by vsimakhin** [comment]
Looks like I wrongly used the styles/classes for the submenu. The fix is coming soon with 2.35.1 version
