### ISSUE TITLE
Add horizontal scrolling logbook table

### ISSUE THREAD

**Issue by maesteve** [vsimakhin/web-logbook#218]
When accessing via mobile or tablet, the complete content of the logbook table is not displayed. Add horizontal scrolling to the table, similar to the statistics tables, to be able to view all the values.

**Comment by vsimakhin** [comment]
The logbook table on the mobile devices should show less columns. Can you send a screenshot how it looks on your device?

**Comment by maesteve** [comment]
![IMG_0236](https://github.com/vsimakhin/web-logbook/assets/3056065/f8cb9143-7d74-4ab6-9a0c-20390eef5f4e)

**Comment by maesteve** [comment]
Mobile

![IMG_9349](https://github.com/vsimakhin/web-logbook/assets/3056065/e4db77f5-0ef9-422a-8784-832885b70d95)

**Comment by maesteve** [comment]
With horizontal scrolling stats table mobile. 

![IMG_9350](https://github.com/vsimakhin/web-logbook/assets/3056065/876cd4b2-eb49-4332-b8e7-2b6feb4f04bf)

**Comment by vsimakhin** [comment]
Thank you! Will check it

**Comment by maesteve** [comment]
It still doesn't work. There is no horizontal scroll for all the columns. Now there is a small scroll, but it doesn't cover all the values.

Checked on tablet and mobile.
