### ISSUE TITLE
Issue #218 Add horizontal scrolling logbook table

### ISSUE THREAD

**Issue by maesteve** [vsimakhin/web-logbook#229]
It still doesn't work. There is no horizontal scroll for all the columns. Now there is a small scroll, but it doesn't cover all the values.

The horizontal scroll in the statistics tables works correctly.

Checked on tablet and mobile.

**Comment by vsimakhin** [comment]
oh, you mean that even on mobile devices it should show the full logbook table withou hiding the columns?

**Comment by maesteve** [comment]
Exact. Same as in statistics tables, all columns are shown and you can scroll horizontally
