### ISSUE TITLE
Failing to execute in old ARM processor

### ISSUE THREAD

**Issue by dimoniet** [vsimakhin/web-logbook#230]
It seems that from version 3.34, where GO was upgraded to 1.21, the logbook is not working on old ARM processors. The problem can be that default ARM version from 1.21 is 7, and despite the app would work on 5 and 6, you have to set it when compiling.

Example:
env GOOS=linux GOARCH=arm GOARM=6 /usr/local/go1.21.8/bin/go build web-logbook.go

**Comment by dimoniet** [comment]
I managed to compile and run it on my old raspberry with the GOARM parameter, hope this helps!

**Comment by vsimakhin** [comment]
Thanks! I will update the build script

**Comment by vsimakhin** [comment]
there will be 2 sets of binaries for arm32
```
./dist/web-logbook-linux-arm-6.tar.gz 
./dist/web-logbook-linux-arm-7.tar.gz
```
