### ISSUE TITLE
Export with extended format breaks the page

### ISSUE THREAD

**Issue by dimoniet** [vsimakhin/web-logbook#239]
If you enable the extended format on export pages, it does not modify any column width, but adds a new column with the simulator date. This breaks the whole page:

A4 example:
![image](https://github.com/vsimakhin/web-logbook/assets/1335194/b2f701b2-3373-4449-bf22-b010cbb8a515)

A5 example:
![image](https://github.com/vsimakhin/web-logbook/assets/1335194/d72c8107-85b4-4791-a929-dc5ceef72c97)

**Comment by vsimakhin** [comment]
Wow... ok, will check it

**Comment by vsimakhin** [comment]
looks like I lost some small but very important part of the code when I was updating pdf lib for export. The bug was introduced in v2.34.0. Going through the test and will release a new version soon
