### ISSUE TITLE
make build - failed

### ISSUE THREAD

**Issue by Jacopx** [vsimakhin/web-logbook#246]
Hi dear,

I've just updated the release on my test environment, I got this problem:

```
[root@logbook /logbook]# make build
Cleaning...
Cleaned!
Building...
# modernc.org/sqlite
/root/go/pkg/mod/modernc.org/sqlite@v1.32.0/fcntl.go:27:16: undefined: runtime.Pinner
note: module requires Go 1.20
*** Error code 2

Stop.
make: stopped in /logbook
```

I'm operating it in FreeBSD 13.1-RELEASE-p9 amd64.

Let me know if you need something to test.

**Comment by vsimakhin** [comment]
which go version do you have?

**Comment by Jacopx** [comment]
> which go version do you have?

I was using an older version, so I have updated to: `go version go1.21.12 freebsd/amd64` previously it was something like: 1.19 

But now seems to arise a different problem, and I'm pretty sure is related to the Go version:

```
[root@logbook /logbook]# ./dist/web-logbook -port 80
INFO	2024/08/28 15:50:45 Web Logbook v2.41.0 is ready on http://localhost:80
ERROR	2024/08/28 15:50:48 handlers_logbook.go:25: SQL logic error: no such column: update_time (1)
```

From your commit seems that the version used is 1.21.13 but the package manager show that this is the latest version available.

**Comment by vsimakhin** [comment]
Any 1.21.x version is ok. The error is related to the missing column in the database view. And you somehow still have an older version of the view without this column. I will prepare a fix, which will recreate the view.

As a temporary solution, you can drop the view `logbook_view` in the database and then restart the app - it will create a new one.
