### ISSUE TITLE
ARM v6 - App not loading because of database

### ISSUE THREAD

**Issue by dimoniet** [vsimakhin/web-logbook#254]
I've just updated the executable file in my raspberry with the ARMv6 latest version and it throws an error:

**ERROR   2024/09/12 10:24:19 main.go:162: database disk image is malformed (11)**

I had a recent backup in my computer of the database, uploaded it to my raspberry but still same error. 

Windows version 2.42 and ARMv6 version 2.41 work ok, it's only latest version in ARMv6

**Comment by vsimakhin** [comment]
I will close it for now, since I cannot do anything with it :( All depends on the libs which used by MySQL driver. I hope there will be some update which will still support older ARM arch
