### ISSUE TITLE
Upload attachements in just created flight entry

### ISSUE THREAD

**Issue by Jacopx** [vsimakhin/web-logbook#258]
Hi dear,

when you create a new flight entry, save and then try to upload immediately an attachements, without refreshing or changing page, the system prompt you with positive results but then is missing.

![immagine](https://github.com/user-attachments/assets/e8d44a7e-266e-4c24-9181-1e17677d76f5)

Let me know, not urgent since is working changing page and reopening it.

v2.43

**Comment by vsimakhin** [comment]
Thanks! Will release a fix soon
