### ISSUE TITLE
SQL logic error: near ")": syntax error (1) when creating license

### ISSUE THREAD

**Issue by bbqman7089** [vsimakhin/web-logbook#262]
When creating a license, an error message pops up. It reads 

SQL logic error: near ")": syntax error (1)

![image](https://github.com/user-attachments/assets/1bf52b13-23f1-41d0-9b96-cdb6284c16b3)

All text boxes are filled out with no special characters (unless the slashes in the dates count)

**Comment by vsimakhin** [comment]
Thanks! Will check it...

**Comment by vsimakhin** [comment]
Found the bug, looks like some typo left after a previous big clean up. Will release a new version soon
