### ISSUE TITLE
Error in Database - AJAX error (chrome)

### ISSUE THREAD

**Issue by ken340** [vsimakhin/web-logbook#265]
There is a bug when using chrome 

DataTables warning: table id=logbook - Ajax error. For more information about this error, please see https://datatables.net/tn/7

Additional Info: errors when using localhost or direct IP address from a local network,

it works perfectly on Firefox.

**Comment by vsimakhin** [comment]
Hey! Can you please add some screenshots and steps when it's happening? I tried several options and cannot reproduce it.

**Comment by mfeo15** [comment]
Just to complete @ken340 comment above. When upgrading to v2.43.2 I also experience the same error in Chrome once I wanted to reconnect to the logbook. It was occuring in Chrome only, no issue with Edge for example. The pop-up error said exactlz what is mentioned above and the tables in the logbook were empty.

One day later, I have now reconnected trough Chrome and it all works fine. Guess there might have been a bug that auto-fixed itself after a certain amount of time?

**Comment by vsimakhin** [comment]
Ok... so it happens during the first load of the page? Currently during the start the app recreates the main view in the database (just in case some DB structure changes during the new release), which may cause the error. That is fixable :)
