### ISSUE TITLE
What is the source of the airport DB? Any way of adding aerodromes?

### ISSUE THREAD

**Issue by hisetip** [vsimakhin/web-logbook#65]
My home aerodrome (LPSO) is not on the airport database. That kind of sucks because the maps feature ends up being a bit useless for my use case. Any way to add it to the database? Or for me to manually do it? (Preferentially a way that wouldn't break "update function" of the database).

_"ERROR	2022/10/27 15:37:44 handlers_airport.go:24: cannot find LPSO in the database - sql: no rows in result set"_

**Comment by vsimakhin** [comment]
Hey! I created a pull request https://github.com/mwgg/Airports/pull/77 to the repository with airports DB. Once it's merged, I will sync my local one https://github.com/vsimakhin/Airports/ and you will be able to get it in the app.

**Comment by hisetip** [comment]
Hey! I believe that they already merged your pull req. Thank you for the quick response and the great work!

**Comment by vsimakhin** [comment]
Yep. I updated the local fork, now just run update in the "settings" page

**Comment by hisetip** [comment]
Worked perfectly. Thanks again.
