### ISSUE TITLE
STATS - Aircraft class totals

### ISSUE THREAD

**Issue by dimoniet** [vsimakhin/web-logbook#67]
If you have an aircraft type that is C172, and another that is C172-SEA, the query sure has a like **%type%** so time from first is added to second.

In the attached image, C172SEA time should be 9:13 instead of 10:43. Time from C172LAND is added to C172SEA.

![image](https://user-images.githubusercontent.com/1335194/198869803-be9f5abb-aae3-4b35-9637-b316512d8e72.png)

![image](https://user-images.githubusercontent.com/1335194/198869861-b1adae91-bf9a-4d78-8a8f-4381fa9f94f4.png)

![image](https://user-images.githubusercontent.com/1335194/198869775-9a269330-0aca-4264-b59c-c0cee966bb97.png)

I hope I have described the issue well :)

**Comment by vsimakhin** [comment]
Right, good point. Will take a look

**Comment by vsimakhin** [comment]
new version with bugfix (I hope:) ) released

**Comment by dimoniet** [comment]
Tested version 2.7.1 and now it seems to work properly! Thanks!!
