### ISSUE TITLE
Add date range filter

### ISSUE THREAD

**Issue by dimoniet** [vsimakhin/web-logbook#72]
It would be great to add a date range filter in every part of the logbook, export included

**Comment by vsimakhin** [comment]
Do you mean sort of the "search" field but for the date range? ![image](https://user-images.githubusercontent.com/139220/201174446-62fa0141-3736-47de-a3fd-ed315a4abc79.png)

**Comment by dimoniet** [comment]
Yes, a field to filter flights between two different dates. Something like that:

![image](https://user-images.githubusercontent.com/1335194/202118786-9d02e288-09a6-48c5-9df6-d2c534de243e.png)

**Comment by vsimakhin** [comment]
:+1:

**Comment by vsimakhin** [comment]
Oh yeah, almost works as a charm :) need to test it a little but more. Will probably release it next week
![image](https://user-images.githubusercontent.com/139220/202495373-551455b2-b98c-47e9-bfb8-940e80bd93b0.png)
