### ISSUE TITLE
Adding flying limitations

### ISSUE THREAD

**Issue by Jacopx** [vsimakhin/web-logbook#78]
Could be useful, maybe in the "stats" page, the computation of the flying limitations of EASA, daily, 7 days, 14 days, etc...

A really love this project and I'd like to contibuting.

**Comment by vsimakhin** [comment]
Yep, I was thinking to mark the values in red color if they exceed the limits, but it would be already "too late"

**Comment by Jacopx** [comment]
Maybe a simple computation that shows how much you time available remains in the different time frame.

**Comment by vsimakhin** [comment]
ok, will take a look after NY and holidays

**Comment by Jacopx** [comment]
Thanks for the effort, I'm tesing and I will get some feedback

**Comment by Jacopx** [comment]
Thanks for the effort, I will test it asap.

**Comment by vsimakhin** [comment]
I still didn't release it to the main branch, need to test it a little bit more
