### ISSUE TITLE
 Attach signature to export pdf

### ISSUE THREAD

**Issue by maesteve** [vsimakhin/web-logbook#84]
Attach signature in png format in Settings option and include signature when exporting in pdf.

**Comment by vsimakhin** [comment]
looks like a good lib to use as a signature pad https://github.com/szimek/signature_pad

**Comment by vsimakhin** [comment]
![image](https://user-images.githubusercontent.com/139220/218159528-e018da9e-2175-4c47-9703-c20610996462.png)
