### ISSUE TITLE
Option to hide fields in the flight form

### ISSUE THREAD

**Issue by maesteve** [vsimakhin/web-logbook#86]
"Ability to specify which fields are displayed in the flight creation form. For example, the ability to hide Simulator Type and Time, MCC, ... This makes it easier to enter a flight.

**Comment by vsimakhin** [comment]
Since I'm not a UI developer and I have a limited background in web dev, I don't know how to make it properly, so hiding some fields will not brake a layout. 

You don't need to fill in all the fields, you can just skip them and leave them empty
