### ISSUE TITLE
Add a new column with the flights of the last 12 months in Stats Total

### ISSUE THREAD

**Issue by maesteve** [vsimakhin/web-logbook#87]
In order to renew some certifications, it is necessary to have a minimum number of flights in the last 12 months before they expire. This new column would make it easier to track the flights needed to renew the certifications.

**Comment by vsimakhin** [comment]
There is a `Landings (day/night)` field, or you mean something different?

**Comment by maesteve** [comment]
Add a new column with calculations for all rows of flights in the last 12 months to date. Attached screenshot.

![stats](https://user-images.githubusercontent.com/3056065/212485367-bc0bf38c-6ae4-41b7-9642-f16e2427471a.png)

**Comment by vsimakhin** [comment]
got it
