### ISSUE TITLE
Replace SE or ME time in logbook by checked or not

### ISSUE THREAD

**Issue by maesteve** [vsimakhin/web-logbook#90]
indication if the aircraft is SE or ME, if applicable.

Page 31
https://www.easa.europa.eu/sites/default/files/dfu/Part-FCL.pdf

I attach an example

![271466-72725](https://user-images.githubusercontent.com/3056065/212982435-a0c7e87b-deec-4d73-8c9b-61cfe7f7682e.png)

**Comment by vsimakhin** [comment]
Was thinking about that, I probably will add it as an option in the settings page. I personally prefer the full time field instead of the check box
