### ISSUE TITLE
Add new date column in FSTD session

### ISSUE THREAD

**Issue by maesteve** [vsimakhin/web-logbook#91]
for each FSTD session, if applicable:
(iii) date;

Page 31
https://www.easa.europa.eu/sites/default/files/dfu/Part-FCL.pdf

I attach an example

![271466-72725](https://user-images.githubusercontent.com/3056065/212983668-4e1b164b-2fa8-4e9c-8f3e-6059c90bb831.png)

But hours and minutes in the same cell.

**Comment by vsimakhin** [comment]
I think that's not necessary and overkill to have 2 date colums, you just use the date from the first column 
![image](https://user-images.githubusercontent.com/139220/213131261-e83ecec6-ece9-4885-b24e-45d21bf9a297.png)

**Comment by maesteve** [comment]
The first date is for a flight, if it is a simulator that column should not be completed and if the date of the column FSTD session.

(a) The record of the flights flown should contain at least the following information:
(2) for each flight:
(ii) date of flight;

for each FSTD session, if applicable:
(iii) date;
